GradeSystem/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="Index.html"), name="home"),
    path('student/', include('student.urls')),
    path('admin/', admin.site.urls),
]

student/urls.py
from django.urls import path

from .views import StudentList, StudentDetail, StudentCreate, StudentUpdate, StudentDelete, StudentsGrades, \
    StudentsRank, SubjectScores, GradeCreate, GradeUpdate, GradeDelete, searchAutocomplete

app_name = "student"

urlpatterns = [
    path('', StudentList.as_view(), name='list'),
    path('<int:pk>', StudentDetail.as_view(), name='detail'),
    path('create', StudentCreate.as_view(), name='create'),
    path('<int:pk>/update', StudentUpdate.as_view(), name='update'),
    path('<int:pk>/delete', StudentDelete.as_view(), name='delete'),
    path('<int:pk>/grade/create', GradeCreate.as_view(), name='create_grade'),
    path('<int:studentId>/grade/<int:pk>/update', GradeUpdate.as_view(), name='update_grade'),
    path('<int:studentId>/grade/<int:pk>/delete', GradeDelete.as_view(), name='delete_grade'),
    path('grades', StudentsGrades.as_view(), name='grades'),
    path('rank', StudentsRank.as_view(), name='rank'),
    path('subjects', SubjectScores.as_view(), name='subjects'),
    path('autoComplete', searchAutocomplete, name='autoComplete')
]

student/models.py
from django.db import models
from django.urls import reverse
from django.db.models import Q
from django.shortcuts import get_object_or_404
from django.core.exceptions import ValidationError

from student.Exceptions import GradeExistedError, GradeNotFoundError

def validatePhone(value):
    if not value.isnumeric():
        raise ValidationError("Phone should be numeric.")
    elif len(value) != 10:
        raise ValidationError("Phone should be exactly 10 digits.")
    elif not value.startswith("09"):
        raise ValidationError("Phone should start with '09'")

def validateGrade(value):
    if not 0 <= value <= 100:
        raise ValidationError("Grade should be between 0 and 100.")    
    
class Student(models.Model):
    firstName = models.CharField(max_length=20)
    lastName = models.CharField(max_length=20)
    phone = models.CharField(unique=True, max_length=20, validators=[validatePhone])

    def __str__(self):
        return self.fullName

    @property
    def fullName(self):
        return f"{self.firstName} {self.lastName}"

    def save(self):
        self.firstName = self.firstName.capitalize()
        self.lastName = self.lastName.capitalize()
        super().save()

    def get_absolute_url(self):
        return reverse("student:detail", kwargs={"pk": self.pk})

    def getGrades(self):
        grades = Grade.objects.filter(student__id=self.pk)
        return grades

    def addGrade(self, testNo, chinese, english, math):
        obj, created = Grade.objects.get_or_create(testNo=testNo, student=self, defaults={"chinese": chinese, "english": english, "math": math})
        if not created:
            # TODO: fix validation
            raise GradeExistedError()
        return obj, created

    # def deleteGrade(self, testNo):
    #     grade = Grade.objects.get(Q(student=self) & Q(testNo=testNo))
    #     if grade:
    #         grade.delete()
    #     else:
    #         raise GradeNotFoundError
    #     return grade

class Grade(models.Model):
    testNo = models.PositiveIntegerField(blank=True)
    chinese = models.DecimalField(max_digits=5, decimal_places=2, validators=[validateGrade])
    english = models.DecimalField(max_digits=5, decimal_places=2, validators=[validateGrade])
    math = models.DecimalField(max_digits=5, decimal_places=2, validators=[validateGrade])
    student = models.ForeignKey(Student, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"{self.student}: #{self.testNo}"

    @property
    def total(self):
        return self.chinese + self.english + self.math
    
    @property
    def average(self):
        return round(self.total / 3, 2)

    @property
    def allSubjects(self):
        return [self.chinese, self.english, self.math]

    def get_absolute_url(self):
        return reverse("student:detail", kwargs={"pk": self.student.pk})

student/forms.py
from django import forms
from django.forms import ModelForm

from .models import Student, Grade

class CUStudentForm(ModelForm):
    class Meta:
        model = Student
        fields = ["firstName", "lastName", "phone"]
        labels = {
            "firstName": "First Name",
            "lastName": "Last Name",
            "phone": "Phone"
        }
        widgets = {
            "firstName": forms.TextInput(attrs={"class": "form-control"}),
            "lastName": forms.TextInput(attrs={"class": "form-control"}),
            "phone": forms.TextInput(attrs={"class": "form-control"})
        }


class CUGradeForm(ModelForm):
    class Meta:
        model = Grade
        fields = ["testNo", "chinese", "english", "math"]
        labels = {
            "testNo": "Test Number"
        }
        widgets = {
            "testNo": forms.NumberInput(attrs={"class": "form-control"}),
            "chinese": forms.NumberInput(attrs={"class": "form-control"}),
            "english": forms.NumberInput(attrs={"class": "form-control"}),
            "math": forms.NumberInput(attrs={"class": "form-control"}),
        }

student/views.py
from django.shortcuts import render, reverse, redirect, get_object_or_404
from django.db.models import Q, Value
from django.urls import reverse_lazy
from django.views.generic import View, TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView
from django.http import JsonResponse
from django.db.models.functions import Concat
from django.core.paginator import Paginator
from student.models import Student, Grade
from student.HelperFunction import *
from .forms import CUStudentForm, CUGradeForm
from student.Exceptions import GradeExistedError


class StudentList(ListView):
    model = Student
    template_name = "student/StudentList.html"
    context_object_name = "students"
    paginate_by = 5

    def get_queryset(self):
        qs = super().get_queryset()
        name = self.request.GET.get("name")
        if name:
            result = searchStudent(name)
            if result:
                return result
            else:
                return []
        else:
            return qs
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        name = self.request.GET.get("name")
        context["name"] = name
        return context


class StudentDetail(DetailView):
    model = Student
    template_name = "student/StudentDetail.html"
    context_object_name = "student"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["grades"] = self.object.getGrades()
        context["paginator"] = Paginator(context["grades"], 5)
        return context


class StudentCreate(CreateView):
    model = Student
    form_class = CUStudentForm
    context_object_name = "form"
    template_name = "student/Form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Add a Student"
        return context


class StudentUpdate(UpdateView):
    model = Student
    form_class = CUStudentForm
    context_object_name = "form"
    template_name = "student/Form.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = f"Update {self.object.fullName}'s information"
        return context


class StudentDelete(DeleteView):
    model = Student
    success_url = reverse_lazy("student:list")


class GradeCreate(View):
    def get(self, request, pk):
        form = CUGradeForm()
        student = get_object_or_404(Student, pk=pk)
        title = f"Add Grade for {student.fullName}"
        return render(request, "student/Form.html", {"form": form, "title": title})

    def post(self, request, pk):
        form = CUGradeForm(request.POST)
        student = get_object_or_404(Student, pk=pk)
        title = f"Add Grade for {student.fullName}"
        if form.is_valid():
            testNo, chinese, english, math = form.cleaned_data.values()
            try:
                grade, _ = student.addGrade(testNo, chinese, english, math)
                return redirect(grade)
            except GradeExistedError as e:
                errorMessage = str(e)
                return render(request, "student/Form.html", {"form": form, "title": title, "errorMessage": errorMessage})
        return render(request, "student/Form.html", {"form": form, "title": title})


class GradeUpdate(UpdateView):
    model = Grade
    form_class = CUGradeForm
    template_name = "student/Form.html"
    context_object_name = "form"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = f"Update Test {self.object.testNo} of {self.object.student.fullName}"
        return context


class GradeDelete(DeleteView):
    model = Grade
    def get_success_url(self):
        return reverse('student:detail', kwargs={"pk": self.object.student.pk})

    # def post(self, request, pk, testNo):
    #     student = get_object_or_404(Student, pk=pk)
    #     student.deleteGrade(testNo)
    #     return redirect('student:detail', pk=pk)


class StudentsGrades(TemplateView):
    template_name = "student/StudentsGrades.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['testNumbers'] = getAllTestNumbers()
        context['grades'] = Grade.objects.all()
        return context


class StudentsRank(TemplateView):
    template_name = "student/StudentsRank.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['testsRank'] = getTestsRank()
        return context

class SubjectScores(TemplateView):
    template_name = "student/SubjectScores.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['subjectsScores'] = getSubjectsScores()
        return context

def searchAutocomplete(request):
    name = request.GET.get("q")
    if name:
        students = searchStudent(name)
        result = [student.fullName for student in students]
        return JsonResponse(result, safe=False)
    else:
        return JsonResponse([], safe=False)

student/templates/student/BackArrow.html
<a href="javascript:history.go(-1)" class="btn pl-0">
    <i class="fas fa-arrow-left"></i>
    Back
</a>

student/templates/student/DeleteGradeModal.html
<div 
    class="modal fade" 
    id="deleteGradeModals{{ student.id }}t{{ grade.testNo }}" 
    data-backdrop="static" 
    data-keyboard="false" 
    tabindex="-1" 
    aria-labelledby="deleteGradeLabel" 
    aria-hidden="true"
>
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
            <h3 class="modal-title" id="deleteGradeLabel">
              About to delete a Grade Record
            </h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <form action="{% url 'student:delete_grade' student.pk grade.pk %}" method="POST">
          {% csrf_token %}
          <div class="modal-body">
            <h5>Are you sure you want to delete Test {{ grade.testNo }} from {{ student.firstName }}?</h5>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-primary">Yes</button>
          </div>
        </form>
      </div>
    </div>
  </div>

student/templates/student/DeleteStudentModal.html
<div 
    class="modal fade" 
    id="deleteStudentModal{{ student.id }}" 
    data-backdrop="static" 
    data-keyboard="false" 
    tabindex="-1" 
    aria-labelledby="deleteGradeLabel" 
    aria-hidden="true"
>
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="deleteGradeLabel">
          About to delete a Student
        </h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <form action="{% url 'student:delete' student.pk %}" method="POST">
        {% csrf_token %}
        <div class="modal-body">
          <h5>Are you sure you want to delete {{ student.fullName }}?</h5>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary">Yes</button>
        </div>
      </form>
    </div>
  </div>
</div>

student/templates/student/Form.html
{% extends 'Base.html' %}
{% block content %}
<style>
    .warning {
        color: red;
        margin-top: 5px;
        margin-bottom: 0;
    }

    .inputWarning {
        border: 1px solid red;
    }
</style>

<h4 class="mt-4 mb-5">{{ title }}</h4>
<form method="POST" id="commonForm">
    {% csrf_token %}
    {% for field in form %}
      <div class="form-group row col-2">
          {{ field.label_tag }}
          {{ field }}
          {{ field.errors }}
      </div>
    {% endfor %}
    <div class="mb-2" style="color: red">{{ errorMessage }}</div>
    <input id="submitBtn" class="btn text-white" type="button" value="Submit" style="background-color: #0062cc;">
</form>

{% load static %}
<script type="text/javascript" src="{% static 'js/FormValidation.js' %}"></script>
{% endblock %}

student/templates/student/StudentDetail.html
{% extends 'Base.html' %}

{% block content %}
<div class="card mt-3">
  <div class="card-body">
    <h2 class="card-title mb-5">{{ student.fullName }}'s Information</h2>
    <ul class="nav nav-tabs nav-fill" id="myTab" role="tablist">
      <li class="nav-item" role="presentation">
        <a 
          class="nav-link active" 
          id="grades-tab" 
          data-toggle="tab" 
          href="#grades" 
          role="tab" 
          aria-controls="grades" 
          aria-selected="false"
        >
          <h6>Grades</h6>
        </a>
      </li>
      <li class="nav-item" role="presentation">
        <a 
          class="nav-link" 
          id="profile-tab" 
          data-toggle="tab" 
          href="#profile" 
          role="tab" 
          aria-controls="profile" 
          aria-selected="true"
        >
          <h6>Profile</h6>
        </a>
      </li>
    </ul>
    <div class="tab-content px-3 py-5" id="myTabContent">
      <div class="tab-pane fade show active" id="grades" role="tabpanel" aria-labelledby="grades-tab">
        <a 
          href="{% url 'student:create_grade' student.pk %}" 
          type="button"
          class="btn text-white mb-3" 
          style="background-color: #0062cc;"
        >
          Add Grade
        </a>
        <table class="table">
          <thead>
            <tr>
              <th style="width: 2%"></th>
              <th scope="col" style="width: 10%">Test#</th>
              <th scope="col" style="width: 12%">Chinese</th>
              <th scope="col" style="width: 12%">English</th>
              <th scope="col" style="width: 12%">Math</th>
              <th scope="col" style="width: 12%">Total</th>
              <th scope="col" style="width: 12%">Average</th>
              <th></th>
            </tr>
          </thead>
          <tbody>
            {% if grades %}
              {% for grade in grades %}
                <tr>
                  <td></td>
                  <td>{{ grade.testNo }}</td>
                  <td>{{ grade.chinese }}</td>
                  <td>{{ grade.english }}</td>
                  <td>{{ grade.math }}</td>
                  <td>{{ grade.total }}</td>
                  <td>{{ grade.average }}</td>
                  <td>
                    <a type="button" href="{% url 'student:update_grade' student.pk grade.pk %}" class="btn btn-info">
                      <i class="far fa-edit"></i>
                    </a>
                    <button 
                      class="btn btn-danger"
                      data-toggle="modal" 
                      data-target="#deleteGradeModals{{ student.id }}t{{ grade.testNo }}"
                    >
                      <i class="far fa-trash-alt"></i>
                    </button>
                  </td>
                </tr>
                {% include "student/DeleteGradeModal.html" %}
              {% endfor %}
            {% else %}
              <tr>
                <td colspan="8" class="py-4">
                  <h5 class="text-secondary" style="text-align: center;">No Grades Yet</h5>
                </td>
              </tr>
            {% endif %}
          </tbody>
        </table>
        {% include 'Paginator.html' %}
      </div>
      <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
        <a 
          href="{% url 'student:update' student.pk %}" 
          type="button" 
          class="btn text-white mb-3" 
          style="background-color: #0062cc;"
        >
          Edit Profile
        </a>
        <div class="card">
          <div class="card-body">
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">First Name</h6>
              </div>
              <div class="col-sm-9">
                {{ student.firstName }}
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Last Name</h6>
              </div>
              <div class="col-sm-9">
                {{ student.lastName }}
              </div>
            </div>
            <hr>
            <div class="row">
              <div class="col-sm-3">
                <h6 class="mb-0">Phone</h6>
              </div>
              <div class="col-sm-9">
                {{ student.phone }}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

student/templates/student/StudentList.html
{% extends 'Base.html' %}

{% block content %}
<h3 class="mt-4 mb-5">Student List</h3>
<div class="d-flex justify-content-between align-items-center mb-3 mt-5">
  <a 
    href="{% url 'student:create' %}" 
    type="button" 
    class="btn text-white" 
    style="background-color: #0062cc;"
  >
    Add a Student
  </a>
  <form method="GET" class="d-flex form-inline my-2 my-lg-0">
    <input 
      class="form-control mr-sm-2 basicAutoComplete" 
      data-url="{% url 'student:autoComplete' %}"
      autocomplete="off"
      type="search" 
      placeholder="Search" 
      autocomplete="on"
      name="name"
      value="{% if name != None %}{{ name }}{% endif %}"
      style="width: 200px"
    >
    <button class="btn px-0" type="submit">
      <i class="fas fa-search" style="font-size: 1.5rem"></i>
    </button>
  </form>
</div>
<div class="card">
  <table class="table mb-0">
    <thead>
      <tr>
        <th style="width: 3%"></th>
        <th scope="col">ID</th>
        <th scope="col">Name</th>
        <th scope="col">Phone</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% if students %}
        {% for student in students %}
          <tr>
            <td></td>
            <th scope="row" class="py-4" style="width: 10%">{{ student.id }}</th>
            <td style="width: 15%"><h6>{{ student.fullName }}</h6></td>
            <td style="width: 15%">{{ student.phone }}</td>
            <td>
              <div class="d-flex">
                <a 
                  href="{% url 'student:detail' student.pk %}" 
                  type="button" 
                  class="btn btn-info mr-3"
                >
                  Detail
                </a>
                <button 
                  class="btn btn-danger" 
                  data-toggle="modal" 
                  data-target="#deleteStudentModal{{ student.id }}"
                >
                  Delete
                </button>
              </div>
            </td>
          </tr>
          {% include "student/DeleteStudentModal.html" %}
        {% endfor %}
      {% else %}
        <tr>
          <td colspan="5" class="py-4" style="text-align: center;">
            <h5 class="text-secondary">No Result</h5>
          </td>
        </tr>
      {% endif %}
    </tbody>
  </table>
</div>
<div>
  {% include 'Paginator.html' %}
</div>


<script>
  $('.basicAutoComplete').autoComplete({'minLength': 1});
</script>
{% endblock %}

student/templates/student/StudentsGrades.html
{% extends 'Base.html' %}

{% block content %}
<h3 class="mt-4 mb-5">Students Grades</h3>
<ul class="nav nav-tabs" id="myTab" role="tablist">
  {% for testNumber in testNumbers %}
    <li class="nav-item" role="presentation">
      {% if forloop.counter == 1 %}
        <a class="nav-link active" id="t{{ testNumber }}" data-toggle="tab" href="#p{{ testNumber }}" role="tab" aria-controls="p{{ testNumber }}" aria-selected="true">Test {{ testNumber }}</a>
      {% else %}
        <a class="nav-link" id="t{{ testNumber }}" data-toggle="tab" href="#p{{ testNumber }}" role="tab" aria-controls="p{{ testNumber }}" aria-selected="true">Test {{ testNumber }}</a>
      {% endif %}
    </li>
  {% endfor %}
</ul>
<div class="tab-content py-3" id="myTabContent">
  {% for testNumber in testNumbers %}
    {% if forloop.counter == 1 %}
      <div class="tab-pane fade show active" id="p{{ testNumber }}" role="tabpanel" aria-labelledby="t{{ testNumber }}">
    {% else %}
      <div class="tab-pane fade" id="p{{ testNumber }}" role="tabpanel" aria-labelledby="t{{ testNumber }}">
    {% endif %}
      <table class="table table-bordered" style="width: 60%">
        <thead>
          <tr>
            <th scope="col" style="width: 5%">ID</th>
            <th scope="col" style="width: 16%">Name</th>
            <th scope="col" style="width: 10%">Chinese</th>
            <th scope="col" style="width: 10%">English</th>
            <th scope="col" style="width: 10%">Math</th>
            <th scope="col" style="width: 10%">Total</th>
            <th scope="col" style="width: 10%">Average</th>
          </tr>
        </thead>
        {% for grade in grades %}
          {% if grade.testNo == testNumber  %}
            <tbody>
              <tr>
                <td>{{ grade.student.id }}</td>
                <td>{{ grade.student.fullName }}</td>
                <td>{{ grade.chinese }}</td>
                <td>{{ grade.english }}</td>
                <td>{{ grade.math }}</td>
                <td>{{ grade.total }}</td>
                <td>{{ grade.average }}</td>
              </tr>
            </tbody>
          {% endif %}
        {% endfor %}
      </table>
    </div>
  {% endfor %}
</div>

{% endblock %}

student/templates/student/StudentsRank.html
{% extends 'Base.html' %}

{% block content %}
<h3 class="mt-4 mb-5">Students Rank</h3>
<ul class="nav nav-tabs" id="myTab" role="tablist">
  {% for testNumber in testsRank.keys %}
    <li class="nav-item" role="presentation">
      {% if forloop.counter == 1 %}
        <a class="nav-link active" id="t{{ testNumber }}" data-toggle="tab" href="#p{{ testNumber }}" role="tab" aria-controls="p{{ testNumber }}" aria-selected="true">Test {{ testNumber }}</a>
      {% else %}
        <a class="nav-link" id="t{{ testNumber }}" data-toggle="tab" href="#p{{ testNumber }}" role="tab" aria-controls="p{{ testNumber }}" aria-selected="true">Test {{ testNumber }}</a>
      {% endif %}
    </li>
  {% endfor %}
</ul>
<div class="tab-content py-3" id="myTabContent">
  {% for testNumber, grades in testsRank.items %}
    {% if forloop.counter == 1 %}
      <div class="tab-pane fade show active" id="p{{ testNumber }}" role="tabpanel" aria-labelledby="t{{ testNumber }}">
    {% else %}
      <div class="tab-pane fade" id="p{{ testNumber }}" role="tabpanel" aria-labelledby="t{{ testNumber }}">
    {% endif %}
      <table class="table table-bordered" style="width: 60%">
        <thead>
          <tr>
            <th scope="col" style="width: 5%">Rank</th>
            <th scope="col" style="width: 5%">ID</th>
            <th scope="col" style="width: 16%">Name</th>
            <th scope="col" style="width: 10%">Chinese</th>
            <th scope="col" style="width: 10%">English</th>
            <th scope="col" style="width: 10%">Math</th>
            <th scope="col" style="width: 10%">Total</th>
            <th scope="col" style="width: 10%">Average</th>
          </tr>
        </thead>
        {% for grade in grades %}
            <tbody>
              <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ grade.student.id }}</td>
                <td>{{ grade.student.fullName }}</td>
                <td>{{ grade.chinese }}</td>
                <td>{{ grade.english }}</td>
                <td>{{ grade.math }}</td>
                <td>{{ grade.total }}</td>
                <td>{{ grade.average }}</td>
              </tr>
            </tbody>
        {% endfor %}
      </table>
    </div>
  {% endfor %}
</div>
{% endblock %}

student/templates/student/SubjectScores.html
{% extends 'Base.html' %}

{% block content %}
<h3 class="mt-4 mb-5">Subject Scores</h3>
<ul class="nav nav-tabs" id="myTab" role="tablist">
{% for testNumber in subjectsScores.keys %}
  <li class="nav-item" role="presentation">
    {% if forloop.counter == 1 %}
      <a 
        class="nav-link active" 
        id="t{{ testNumber }}" 
        data-toggle="tab" 
        href="#r{{ testNumber }}" 
        role="tab" 
        aria-controls="r{{ testNumber }}" 
        aria-selected="true"
      >
        Test {{ testNumber }}
      </a>
    {% else %}
      <a 
        class="nav-link" 
        id="t{{ testNumber }}" 
        data-toggle="tab" 
        href="#r{{ testNumber }}" 
        role="tab" 
        aria-controls="r{{ testNumber }}" 
        aria-selected="true"
      >
        Test {{ testNumber }}
      </a>
    {% endif %}
  </li>
{% endfor %}
</ul>
<div class="tab-content py-3" id="myTabContent">
  {% for testNumber, scores in subjectsScores.items %}
    {% if forloop.counter == 1 %}
      <div class="tab-pane fade show active" id="r{{ testNumber }}" role="tabpanel" aria-labelledby="t{{ testNumber }}">
    {% else %}
      <div class="tab-pane fade" id="r{{ testNumber }}" role="tabpanel" aria-labelledby="t{{ testNumber }}">
    {% endif %}
        <table class="table table-bordered" style="width: 60%">
          <thead>
            <tr>
              <th scope="col"></th>
              <th scope="col">Chinese</th>
              <th scope="col">English</th>
              <th scope="col">Math</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <th style="width: 20%">Total</td>
              <td>{{ scores.total.chinese }}</td>
              <td>{{ scores.total.english }}</td>
              <td>{{ scores.total.math }}</td>
            </tr>
            <tr>
              <th style="width: 20%">Average</td>
              <td>{{ scores.avg.chinese }}</td>
              <td>{{ scores.avg.english }}</td>
              <td>{{ scores.avg.math }}</td>
            </tr>
          </tbody>
        </table>
      </div>
  {% endfor %}
</div>
{% endblock %}