GradeSystem/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name="Index.html"), name="home"),
    path('student/', include('student.urls')),
    path('admin/', admin.site.urls),
]

student/urls.py
from django.urls import path

from .views import StudentList, StudentDetail, StudentCreate, StudentUpdate, StudentDelete, StudentsGrades, \
    StudentsRank, SubjectScores, GradeCreate, GradeUpdate, GradeDelete, searchAutocomplete

app_name = "student"

urlpatterns = [
    path('', StudentList.as_view(), name='list'),
    path('<int:pk>', StudentDetail.as_view(), name='detail'),
    path('create', StudentCreate.as_view(), name='create'),
    path('<int:pk>/update', StudentUpdate.as_view(), name='update'),
    path('<int:pk>/delete', StudentDelete.as_view(), name='delete'),
    path('<int:pk>/grade/create', GradeCreate.as_view(), name='create_grade'),
    path('<int:studentId>/grade/<int:pk>/update', GradeUpdate.as_view(), name='update_grade'),
    path('<int:studentId>/grade/<int:pk>/delete', GradeDelete.as_view(), name='delete_grade'),
    path('grades', StudentsGrades.as_view(), name='grades'),
    path('rank', StudentsRank.as_view(), name='rank'),
    path('subjects', SubjectScores.as_view(), name='subjects'),
    path('autoComplete', searchAutocomplete, name='autoComplete')
]

templates/Base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   
    {% load static %}
    <link rel="stylesheet" href="{% static 'bootstrap-4.6.0-dist/css/bootstrap.min.css' %}"/>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'bootstrap-4.6.0-dist/js/bootstrap.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/gh/xcash/bootstrap-autocomplete@v2.3.7/dist/latest/bootstrap-autocomplete.min.js"></script>
    <script src="https://kit.fontawesome.com/5e8f848121.js" crossorigin="anonymous"></script>
    

    {% block head %}

      <title>Student Grade System</title>
    
    {% endblock %}
  </head>
  <body>

    {% include 'Navbar.html' %}
    <div class="mx-auto py-4" style="width: 85%">
      {% block content %}
      
      {% endblock %}
    </div>
  </body>
</html>

templates/Index.html
{% extends 'Base.html' %}

{% block content %}
    <div class="jumbotron">
        <h2 class="display-4">Welcome to Students' Grade System!</h2>
        <hr class="my-4">
        <a 
            class="btn btn-lg text-white" 
            href="{% url 'student:list' %}" 
            role="button" 
            style="background-color: #0062cc;"
        >
            View Student's Grades
        </a>
    </div>
{% endblock %}

templates/NavBar.html
<nav 
    class="navbar navbar-expand-lg sticky-top navbar-dark py-3" 
    style="background-color: #0b3a85; padding-left: 7.5%;"
>
    <a class="navbar-brand mr-5" href="{% url 'home' %}">Students' Grade System</a>
    <button 
        class="navbar-toggler" 
        type="button" 
        data-toggle="collapse" 
        data-target="#navbarNav" 
        aria-controls="navbarNav" 
        aria-expanded="false" 
        aria-label="Toggle navigation"
    >
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
        <li class="nav-item mr-3">
            <a class="nav-link" href="{% url 'student:list' %}">Student List</a>
        </li>
        <li class="nav-item dropdown mr-3">
            <a 
                class="nav-link dropdown-toggle" 
                href="#" 
                id="navbarDropdown" 
                role="button" 
                data-toggle="dropdown" 
                aria-haspopup="true" 
                aria-expanded="false"
            >
                Tests
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{% url 'student:grades' %}">View Students' Grades</a>
                <a class="dropdown-item" href="{% url 'student:rank' %}">View Students' Rank</a>
                <a class="dropdown-item" href="{% url 'student:subjects' %}">View Subjects</a>
            </div>
        </li>
    </ul>
    </div>
  </nav>

templates/Paginator.html
{% if paginator.num_pages > 1 %}
  <nav class="mt-3 d-flex justify-content-end">
    <ul class="pagination">
      {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.previous_page_number }}" style="color: #0b3a85">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link">
            <span aria-hidden="true">&laquo;</span>
          </a>
        </li>
      {% endif %}
      
      {% for page in paginator.page_range %}
        {% if page == page_obj.number %}
          <li class="page-item">
            <a class="page-link text-white" href="?page={{ page }}" style="background-color: #0b3a85;">{{ page }}</a>
          </li>
        {% else %}
          <li class="page-item"><a class="page-link" href="?page={{ page }}" style="color: #0b3a85">{{ page }}</a></li>
        {% endif %}
      {% endfor %}

      {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="?page={{ page_obj.next_page_number }}" style="color: #0b3a85">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      {% else %}
        <li class="page-item disabled">
          <a class="page-link">
            <span aria-hidden="true">&raquo;</span>
          </a>
        </li>
      {% endif %}
    </ul>
  </nav>
{% endif %}